# Generated by Django 2.1.7 on 2019-03-13 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afexapp', '0002_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
